baseURL: https://nocue-labs.github.io/nocue/
languageCode: en-us
title: NOCUE

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    style: friendly

menu:
#   main:
#   # individual pages are added to menu in their front matter
#   - identifier: about-us
#     name: About Us
#     url: https://nocue-labs.github.io/nocue/about_us/
#     weight: 10
  # - identifier: blog
  #   name: Blog
  #   url: https://blog.twitter.com/engineering/en_us/topics/open-source
  #   rel: noopener
  #   weight: 20
  
