baseURL: https://nocue-labs.github.io/nocue/
languageCode: en-us
title: NOCUE

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    style: friendly

menu:
  main:
  # individual pages are added to menu in their front matter
  - identifier: blog
    name: Blog
    url: https://blog.twitter.com/engineering/en_us/topics/open-source
    rel: noopener
    weight: 10
  - identifier: status
    name: Status
    url: https://nocue-labs.github.io/nocue/status/
    weight: 20
